### ISSUE TITLE
Doubtful design choice to expose a controller as a second instance of bean

### ISSUE THREAD

**Issue by TimurTechnopolis** [OGSegu/Spring-VK-Bot#4]
https://github.com/OGSegu/Spring-VK-Bot/blob/d9f649ed1e3d77b621b56ebc5681a7c0e0590d44/src/main/java/dev/vk/bot/controller/UpdateExecutor.java#L158

https://github.com/OGSegu/Spring-VK-Bot/blob/d9f649ed1e3d77b621b56ebc5681a7c0e0590d44/src/main/java/dev/vk/bot/controller/UpdateParser.java#L101

Generally it is not a good idea to expose a controller as a bean. In this case it seems that due to usage of `@Bean` the second instance of update executor is created.
It makes sense to extract a separate sub-component and inject it to both places - controller and `src/main/java/dev/vk/bot/service/LobbyService.java`. Another sign of a `smelly code` (see [link1](https://www.red-gate.com/simple-talk/dotnet/net-framework/exploring-smelly-code/#:~:text=%E2%80%9CSmelly%20Code%E2%80%9D%20is%20code%20in,that%20gave%20the%20foul%20smell) or [link2](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%B4_%D1%81_%D0%B7%D0%B0%D0%BF%D0%B0%D1%88%D0%BA%D0%BE%D0%BC) ) is that controller is used from within of a service. Usually these types of components are on the different layers of the application and controller layer is responsible for calling service layer and NOT vice versa to retain loose coupling of the application components (see [link1](https://en.wikipedia.org/wiki/Loose_coupling) or [link2](https://medium.com/german-gorelkin/low-coupling-high-cohesion-d36369fb1be9) )

**Comment by OGSegu** [comment]
Probably fixed in [commit](https://github.com/OGSegu/Spring-VK-Bot/commit/9dbbc2882e0f1a169b476af0c95c9774c7a21619) could you check it, please?
